{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "tam.serviceAccount" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "tam.name" . }}
    chart: {{ template "tam.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
