{{- if  (eq (include "prometheus.enabled" .) "true")  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: tam-kube-state-metrics
    app.kubernetes.io/version: v1.8.0
  name: tam-kube-state-metrics
  namespace: {{ template "monitoring.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tam-kube-state-metrics
subjects:
- kind: ServiceAccount
  name: tam-kube-state-metrics
  namespace: {{ template "monitoring.namespace" . }}
{{- end }}