{{- if  (eq (include "prometheus.enabled" .) "true")  }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: tam-kube-state-metrics
    app.kubernetes.io/version: v1.8.0
    {{- range $key, $val := .Values.service_tam_ksm.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}   
  name: tam-kube-state-metrics
  namespace: {{ template "monitoring.namespace" . }}
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
  - name: telemetry
    port: 8081
    targetPort: telemetry
  selector:
    app.kubernetes.io/name: tam-kube-state-metrics
{{- end }}