---
name: "GitHub Actions Example"

"on":
  pull_request:
  push: { branches: [ dev ] }

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      working-directory: terraform
      TF_WORKSPACE: my-workspace
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1

      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Run Terrascan
        id: terrascan
        uses: accurics/terrascan-action@main
        with:
          iac_type: 'terraform'
          iac_version: 'v14'
          policy_type: 'aws'
          only_warn: true
          iac_dir: terraform
        #sarif_upload: true
        #non_recursive:
        #iac_dir:
        #policy_path:
        #skip_rules:
        #config_path:

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.4

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform init 
        id: init
        run: terraform init
        working-directory: ${{ env.working-directory }}
        env:
          TF_CLI_ARGS_init: "-backend-config=role_arn=arn:aws:iam::078766879797:user/coke -upgrade -reconfigure"
          TF_VAR_assume_role: "arn:aws:iam::078766879797:user/coke"

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color
        working-directory: ${{ env.working-directory }}
        env:
          TF_VAR_assume_role: "arn:aws:iam::078766879797:user/coke"

      - name: Plan output
        id: output
        uses: actions/github-script@v3
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            ### Workspace
            \`${process.env.TF_WORKSPACE}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            \`\`\`hcl
            ${process.env.PLAN}
            \`\`\`
            </details>
            **Pusher**: @${{ github.actor }}
            **Action**: ${{ github.event_name }}
            `;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Terraform apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
        working-directory: ${{ env.working-directory }}
        env:
          TF_VAR_assume_role: "arn:aws:iam::078766879797:user/coke"

      - name: Terraform apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply/helm -auto-approve -input=false
        working-directory: ${{ env.working-directory }}
        env:
          TF_VAR_assume_role: "arn:aws:iam::078766879797:user/coke"

      - name: Install InSpec
        uses: actionshub/chef-install@main
        with:
          channel: current
          project: inspec

      - name: Assume Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::078766879797:user/coke
          role-duration-seconds: 600
          role-skip-session-tagging: true          
